{"cells":[{"cell_type":"code","execution_count":8,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":912,"status":"ok","timestamp":1715790541430,"user":{"displayName":"antonio del trionfo","userId":"08129683538845839311"},"user_tz":-60},"id":"s5vphcRZ5KRo","outputId":"9082ed23-8724-42d9-9a8b-006d2a9ce530"},"outputs":[{"name":"stdout","output_type":"stream","text":["shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected\n","shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/pip3\", line 5, in \u003cmodule\u003e\n","    from pip._internal.cli.main import main\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/main.py\", line 10, in \u003cmodule\u003e\n","    from pip._internal.cli.autocompletion import autocomplete\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/autocompletion.py\", line 10, in \u003cmodule\u003e\n","    from pip._internal.cli.main_parser import create_main_parser\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/main_parser.py\", line 9, in \u003cmodule\u003e\n","    from pip._internal.build_env import get_runnable_pip\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/build_env.py\", line 19, in \u003cmodule\u003e\n","    from pip._internal.cli.spinners import open_spinner\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/spinners.py\", line 9, in \u003cmodule\u003e\n","    from pip._internal.utils.logging import get_indentation\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/utils/logging.py\", line 13, in \u003cmodule\u003e\n","    from pip._vendor.rich.console import (\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/rich/__init__.py\", line 17, in \u003cmodule\u003e\n","    _IMPORT_CWD = os.path.abspath(os.getcwd())\n","OSError: [Errno 107] Transport endpoint is not connected\n","shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected\n","shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/pip3\", line 5, in \u003cmodule\u003e\n","    from pip._internal.cli.main import main\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/main.py\", line 10, in \u003cmodule\u003e\n","    from pip._internal.cli.autocompletion import autocomplete\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/autocompletion.py\", line 10, in \u003cmodule\u003e\n","    from pip._internal.cli.main_parser import create_main_parser\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/main_parser.py\", line 9, in \u003cmodule\u003e\n","    from pip._internal.build_env import get_runnable_pip\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/build_env.py\", line 19, in \u003cmodule\u003e\n","    from pip._internal.cli.spinners import open_spinner\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/spinners.py\", line 9, in \u003cmodule\u003e\n","    from pip._internal.utils.logging import get_indentation\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/utils/logging.py\", line 13, in \u003cmodule\u003e\n","    from pip._vendor.rich.console import (\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/rich/__init__.py\", line 17, in \u003cmodule\u003e\n","    _IMPORT_CWD = os.path.abspath(os.getcwd())\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["# install any necessary packages\n","!pip install -U spacy\n","!pip install spacy_transformers"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":32777,"status":"ok","timestamp":1715790261279,"user":{"displayName":"antonio del trionfo","userId":"08129683538845839311"},"user_tz":-60},"id":"hOHQV9R9p-Op","outputId":"77cf1e6c-dd33-4a38-8826-ca79f24b04e9"},"outputs":[{"name":"stdout","output_type":"stream","text":["Mounted at /content/drive\n","/content/drive/MyDrive/Custom_NER\n","Wed May 15 16:24:20 2024       \n","+---------------------------------------------------------------------------------------+\n","| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |\n","|-----------------------------------------+----------------------+----------------------+\n","| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |\n","| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |\n","|                                         |                      |               MIG M. |\n","|=========================================+======================+======================|\n","|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |\n","| N/A   37C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |\n","|                                         |                      |                  N/A |\n","+-----------------------------------------+----------------------+----------------------+\n","                                                                                         \n","+---------------------------------------------------------------------------------------+\n","| Processes:                                                                            |\n","|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |\n","|        ID   ID                                                             Usage      |\n","|=======================================================================================|\n","|  No running processes found                                                           |\n","+---------------------------------------------------------------------------------------+\n"]}],"source":["# Import the necessary libraries and mount Google Drive to access project files\n","from google.colab import drive\n","drive.mount('/content/drive')\n","\n","# Change the working directory to the project folder\n","%cd \"/content/drive/MyDrive/Custom_NER\"\n","\n","# Import required libraries and install any necessary packages\n","import spacy\n","from spacy.tokens import DocBin\n","from tqdm import tqdm\n","import json\n","\n","# Check the installed version of spaCy\n","spacy.__version__\n","\n","# Check GPU information\n","!nvidia-smi"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"_wWcT5uysj7f"},"outputs":[],"source":["#Annotation created manually with https://tecoholic.github.io/ner-annotator/\n","\n","# Load the annotated data from a JSON file\n","data = json.load(open('/content/drive/MyDrive/Custom_NER/annotations_dataset/annotations.json','r'))\n","\n","# Display the number of items in the dataset\n","len(data)\n","\n","data_cleaned = list(filter(None, data))"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"FrDbmGi1swy4"},"outputs":[],"source":["# Define a function to create spaCy DocBin objects from the annotated data\n","def get_spacy_doc(file, data):\n","  # Create a blank spaCy pipeline\n","  nlp = spacy.blank('en')\n","  db = DocBin()\n","\n","  # Iterate through the data\n","  for text, annot in tqdm(data):\n","    doc = nlp.make_doc(text)\n","    annot = annot['entities']\n","\n","    ents = []\n","    entity_indices = []\n","\n","    # Extract entities from the annotations\n","    for start, end, label in annot:\n","      skip_entity = False\n","      for idx in range(start, end):\n","        if idx in entity_indices:\n","          skip_entity = True\n","          break\n","      if skip_entity:\n","        continue\n","\n","      entity_indices = entity_indices + list(range(start, end))\n","      try:\n","        span = doc.char_span(start, end, label=label, alignment_mode='strict')\n","      except:\n","        continue\n","\n","      if span is None:\n","        # Log errors for annotations that couldn't be processed\n","        err_data = str([start, end]) + \"    \" + str(text) + \"\\n\"\n","        file.write(err_data)\n","      else:\n","        ents.append(span)\n","\n","    try:\n","      doc.ents = ents\n","      db.add(doc)\n","    except:\n","      pass\n","\n","  return db"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true,"base_uri":"https://localhost:8080/"},"id":"4fP7sORgtMCn"},"outputs":[{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-9-87a39f5e3c5d\u003e\", line 2, in \u003ccell line: 2\u003e\n","    from sklearn.model_selection import train_test_split\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1027, in _find_and_load\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1002, in _find_and_load_unlocked\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 945, in _find_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1439, in find_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1408, in _get_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1366, in _path_importer_cache\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-9-87a39f5e3c5d\u003e\", line 2, in \u003ccell line: 2\u003e\n","    from sklearn.model_selection import train_test_split\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1027, in _find_and_load\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1002, in _find_and_load_unlocked\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 945, in _find_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1439, in find_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1408, in _get_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1366, in _path_importer_cache\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-9-87a39f5e3c5d\u003e\", line 2, in \u003ccell line: 2\u003e\n","    from sklearn.model_selection import train_test_split\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1027, in _find_and_load\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1002, in _find_and_load_unlocked\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 945, in _find_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1439, in find_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1408, in _get_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1366, in _path_importer_cache\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["# Split the annotated data into training and testing sets\n","from sklearn.model_selection import train_test_split\n","train, test = train_test_split(data_cleaned, test_size=0.2)\n","\n","# Display the number of items in the training and testing sets\n","len(train), len(test)\n","print(train)\n","# Open a file to log errors during annotation processing\n","file = open('/content/drive/MyDrive/Custom_NER/trained_models/train_file.txt','w')\n","\n","# Create spaCy DocBin objects for training and testing data\n","db = get_spacy_doc(file, train)\n","db.to_disk('/content/drive/MyDrive/Custom_NER/trained_models/train_data.spacy')\n","\n","db = get_spacy_doc(file, test)\n","db.to_disk('/content/drive/MyDrive/Custom_NER/trained_models/test_data.spacy')\n","\n","# Close the error log file\n","file.close()"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":157189,"status":"ok","timestamp":1715706050441,"user":{"displayName":"antonio del trionfo","userId":"08129683538845839311"},"user_tz":-60},"id":"X5cHiV_K4yDl","outputId":"a1bffea6-35ac-4d17-c951-457fa5e7bf6e"},"outputs":[{"name":"stdout","output_type":"stream","text":["\u001b[38;5;4mℹ Saving to output directory:\n","/content/drive/MyDrive/Custom_NER/trained_models/output\u001b[0m\n","\u001b[38;5;4mℹ Using GPU: 0\u001b[0m\n","\u001b[1m\n","=========================== Initializing pipeline ===========================\u001b[0m\n","/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.\n","  _torch_pytree._register_pytree_node(\n","/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.\n","  _torch_pytree._register_pytree_node(\n","\u001b[38;5;2m✔ Initialized pipeline\u001b[0m\n","\u001b[1m\n","============================= Training pipeline =============================\u001b[0m\n","\u001b[38;5;4mℹ Pipeline: ['transformer', 'ner']\u001b[0m\n","\u001b[38;5;4mℹ Initial learn rate: 0.0\u001b[0m\n","E    #       LOSS TRANS...  LOSS NER  ENTS_F  ENTS_P  ENTS_R  SCORE \n","---  ------  -------------  --------  ------  ------  ------  ------\n","  0       0        1292.59    342.70    0.00    0.00    0.00    0.00\n"," 50      50       42545.77  16160.39    0.00    0.00    0.00    0.00\n","100     100        5914.18   4027.05    0.00    0.00    0.00    0.00\n","150     150       26142.92   2505.18   50.00   60.00   42.86    0.50\n","200     200         940.37    242.38   61.54   66.67   57.14    0.62\n","250     250           0.01      0.01   61.54   66.67   57.14    0.62\n","300     300           0.00      0.00   61.54   66.67   57.14    0.62\n","\n","\u001b[31mAborted.\u001b[0m\n"]}],"source":["#!pip install cupy\n","# Train a spaCy NER model using the provided configuration and data\n","!python -m spacy train /content/drive/MyDrive/Custom_NER/config/config.cfg  --output /content/drive/MyDrive/Custom_NER/trained_models/output  --paths.train /content/drive/MyDrive/Custom_NER/trained_models/train_data.spacy  --paths.dev /content/drive/MyDrive/Custom_NER/trained_models/test_data.spacy --gpu-id 0"]}],"metadata":{"accelerator":"GPU","colab":{"authorship_tag":"ABX9TyMIttS6qqukR9BzG20GdhNY","gpuType":"T4","name":"","version":""},"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"name":"python"}},"nbformat":4,"nbformat_minor":0}